### ISSUE TITLE
Execute from docker container

### ISSUE THREAD

**Issue by juanitocalero** [eclipse/capella-xhtml-docgen#179]
Hi,

I'm trying to launch the HTML generation from a Docker container based in Ubuntu 20, installing Capella 5 and the required addons.
The execution fails becuse the code is looking for a graphical display, which of course does not exist inside a docker container. 
Previously I had to install `libswt-gtk-4-java` .

Is this use case contemplated by the tool? I've found this issue in m2doc (https://github.com/ObeoNetwork/Capella-Extensions/pull/24#issuecomment-653617275) and the comments there make me think that it is feasible. In fact, the author says that its code comes from the xhtml-docgen project. 

This is the failure I get (project paths modified):
```
!SESSION 2021-05-13 16:20:58.270 -----------------------------------------------
eclipse.buildId=unknown
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.polarsys.capella.core.commandline.core -appid org.polarsys.kitalpha.doc.gen.business.capella.commandline -filepath /proj.aird -outputfolder /xhtml/export -forceoutputfoldercreation
Command-line arguments:  -os linux -ws gtk -arch x86_64 -application org.polarsys.capella.core.commandline.core -appid org.polarsys.kitalpha.doc.gen.business.capella.commandline -data /g2g/00-gseg -filepath /proj.aird -outputfolder /xhtml/export -forceoutputfoldercreation

!ENTRY org.eclipse.core.resources 2 10035 2021-05-13 16:21:00.517
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.osgi 4 0 2021-05-13 16:21:08.910
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4749)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1130)
        at org.eclipse.swt.widgets.Display.create(Display.java:1070)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:636)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:627)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:776)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:166)
        at org.polarsys.capella.docgen.commandline.HTMLCommandLine.startFakeWorkbench(HTMLCommandLine.java:130)
        at org.polarsys.capella.docgen.commandline.HTMLCommandLine.execute(HTMLCommandLine.java:81)
        at org.polarsys.capella.core.commandline.core.CommandLineApp.launchApp(CommandLineApp.java:138)
        at org.polarsys.capella.core.commandline.core.CommandLineApp.start(CommandLineApp.java:72)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

Isn't the goal of the startFakeWorkbench code avoid creating a real UI session? 

This is my execution:
```
  5 ./capella  -nosplash \
  6         -application org.polarsys.capella.core.commandline.core \
  7         -appid org.polarsys.kitalpha.doc.gen.business.capella.commandline \
  8         -data /proj-folder \
  9         -filepath /proj.aird \
 10         -outputfolder /xhtml/export \
 11         -forceoutputfoldercreation
```

I've found some workarounds creating X11 sessions, but I would prefer to avoid those solutions, complicating unnecessarily a  command line job.

Thanks!

**Comment by juanitocalero** [comment]
@dsryzhov, maybe you could help? 
Thanks in advance!

**Comment by juanitocalero** [comment]
I've managed to do it using Xvfb: `Xvfb :1 -ac -screen 0 1024x768x8 & export DISPLAY=:1` before launching the Capella execution. 
It would be nice to have an official docker template for Capella executions. Thanks!

**Comment by dsryzhov** [comment]
> I've managed to do it using Xvfb: `Xvfb :1 -ac -screen 0 1024x768x8 & export DISPLAY=:1` before launching the Capella execution.
> It would be nice to have an official docker template for Capella executions. Thanks!

Great!

**Comment by arnauddieumegard** [comment]
Hi,

Nice to see that you managed to find a workaround. You are indeed right it should work out of the box.
I will have a look but cannot guarantee when (and if) a solution will be available.
Providing a docker container for Capella command line jobd may indeed be very interesting.

Regards,
Arnaud
